[server]
headless = true
enableCORS = false
port = 8501
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"